version: 2

project_name: xpost

before:
  hooks:
    - go mod tidy

builds:
  - id: xpost
    main: ./
    binary: xpost
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: xpost
    formats:
      - tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
